CREATE DATABASE wifnixdb IF NOT EXISTS;

use wifnix

CREATE TABLE product (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    product VARCHAR(55) NOT NULL,
    details VARCHAR(255) NOT NULL,
    price DECIMAL,
    quantity INT NOT NULL,
    category VARCHAR(55),
    images JSON NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    pass VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    rol VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
)