import Head from "next/head";
import Navbar from "../components/layout/navbar";
import Footer from "../components/layout/footer";
import SocialMedia from "../components/layout/socialmedia";
import About from "../components/About/aboutus";

function AboutUs() {
  return (
    <>
      <Head>
        <title>Sobre Nosotros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/LogoWifnix.svg" />
      </Head>
      <Navbar />
      <About />
      <span className="separador"></span>
      <SocialMedia text={'You have doubts?'} />
      <Footer />
    </>
  );
}

export default AboutUs;
