import Head from "next/head";
import Admin from "../components/admin/administracion";

function Administrador() {
  return (
    <>
      <Head>
        <title>Administration panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/LogoWifnix.svg" />
      </Head>
      <Admin />
    </>
  );
}

export default Administrador;
