import Head from "next/head";
import Menu from "../components/help/menu-help";
import Footer from "../components/layout/footer";
import Navbar from "../components/layout/navbar";
import SocialMedia from "../components/layout/socialmedia";

function Help() {
  return (
    <>
      <Head>
        <title>Servicio de ayuda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/FaviconWifnix.svg" />
      </Head>
      <Navbar />
      <Menu />
      <span className="separador"></span>
      <SocialMedia text={'You have doubts?'} />
      <Footer />
    </>
  );
}

export default Help;
