import Head from "next/head";
import Categories from "../components/Home/categorias";
import Destacados from "../components/Home/destacados";
import Footer from "../components/layout/footer";
import Hero from "../components/Home/hero-calls";
import Marcas from "../components/Home/marcas";
import NavBar from "../components/layout/navbar";
import Ofertas from "../components/Home/ofertas";
import Slider from "../components/Home/slider";
import SocialMedia from "../components/layout/socialmedia";
import Testimonios from "../components/Home/testimonios";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wifnix | Pagina de Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/FaviconWifnix.svg" />
      </Head>
      <NavBar />
      <Slider />
      <Categories />
      <span className="separador"></span>
      <Destacados />
      <span className="separador"></span>
      <Marcas />
      <span className="separador"></span>
      <Ofertas />
      <span className="separador"></span>
      <Hero />
      <Testimonios />
      <span className="separador"></span>
      <SocialMedia />
      <Footer />
    </div>
  );
}
