import Head from "next/head";
import IniciarSesion from "../components/login/login";

function Login() {
  return (
    <>
      <Head>
        <title>Ingresa a tu cuenta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/FaviconWifnix.svg" />
      </Head>
      <IniciarSesion />
    </>
  );
}

export default Login;
