import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import NavBar from "../../components/layout/navbar";
import CatShop from "../../components/Shop/categorieShop";
import ProductId from "../../components/Shop/productID";

function ProductCart() {
  const [product, setProduct] = useState();
  const router = useRouter();

  //En este useEffect se realiza la llamada al producto seleccionado y se muestra en el ProductId
  useEffect(() => {
    const { id } = router.query;
    const GetProduct = async () => {
      const productId = localStorage.getItem("productId");
      const url = `/api/${productId}`;
      try {
        const res = await axios.get(url);
        const product = await res.data;
        setProduct(product);
      } catch (err) {
        console.log(err);
      }
    };
    localStorage.setItem("productId", id);
    GetProduct();
  }, [router.query.id]);

  //console.log(product);

  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/FaviconWifnix.svg" />
        <title>{product ? product.product : "Buscando producto"}</title>
      </Head>
      <NavBar />
      <CatShop />
      <ProductId
        product={product && product.product}
        price={product && product.price}
        quantity={product && product.quantity}
      />
    </div>
  );
}

export default ProductCart;
