import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import NavBar from "../../components/layout/navbar";
import CatShop from "../../components/Shop/categorieShop";
import ProductId from "../../components/Shop/productID";
import Details from "../../components/Shop/detailsID";
import MuestraProducts from "../../components/layout/getproduct";
import Packs from "../../components/Shop/oferts-kits";
import SocialMedia from "../../components/layout/socialmedia";
import Footer from "../../components/layout/footer";
import { Alert } from "@mui/material";

function ProductCart() {
  const [product, setProduct] = useState();
  const [addCart, setAddCart] = useState(false);
  const router = useRouter();

  //En este useEffect se realiza la llamada al producto seleccionado y se muestra en el ProductId
  useEffect(() => {
    const { id } = router.query;
    const GetProduct = async () => {
      const productId = localStorage.getItem("productId");
      const url = `/api/${productId}`;
      try {
        const res = await axios.get(url);
        const product = await res.data;
        setProduct(product);
      } catch (err) {
        //console.log(err);
      }
    };
    localStorage.setItem("productId", id);
    GetProduct();
  }, [router.query.id]);

  //console.log(product);

  const imagen = product?.images?.map((e, index) => {
    return e;
  });

  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/FaviconWifnix.svg" />
        <title>
          {product
            ? `Producto numero ${product.id} || ${product.product}`
            : "Buscando producto"}
        </title>
      </Head>
      <NavBar />
      <CatShop />
      {addCart === true && (
        <Alert
          severity="success"
          className="fixed bottom-2 left-2 bg-green-700 text-zinc-100"
          onClose={addCart === false}
        >
          <p>Se añadio el producto a su carro</p>
        </Alert>
      )}
      <ProductId
        product={product && product.product}
        price={product && product.price}
        quantity={product && product.quantity}
        image={imagen}
        id={product && product.id}
        setAlert={setAddCart}
      />
      <span className="separador"></span>
      <Details />
      <span className="separador"></span>
      <Packs />
      <span className="separador"></span>
      <h2 className="title-section text-3xl md:text-5xl py-2">
        Productos recomendados
      </h2>
      <MuestraProducts />
      <span className="separador"></span>
      <h2 className="title-section text-3xl md:text-5xl py-2">Comparar</h2>
      <MuestraProducts />
      <span className="separador"></span>
      <SocialMedia text={"You have doubts?"} />
      <Footer />
    </div>
  );
}

export default ProductCart;
